
[1m2025-05-01 at 19:44:36 | Toolbox INFO | Starting: LaCAM, {'name': 'LaCAM'}
Traceback (most recent call last):
  File "/mnt/c/Users/Oguzhan Karaarslan/Desktop/repos/pogema-lacam-dcc/algorithms/eval.py", line 57, in <module>
    main()
  File "/mnt/c/Users/Oguzhan Karaarslan/Desktop/repos/pogema-lacam-dcc/algorithms/eval.py", line 52, in main
    evaluation(evaluation_config, eval_dir=eval_dir)
  File "/home/oguzhan/.local/lib/python3.10/site-packages/pogema_toolbox/evaluator.py", line 377, in evaluation
    metrics = balanced_dask_backend(algo_cfg, environment_configs, key)
  File "/home/oguzhan/.local/lib/python3.10/site-packages/pogema_toolbox/evaluator.py", line 285, in balanced_dask_backend
    results = client.gather(futures)
  File "/home/oguzhan/.local/lib/python3.10/site-packages/distributed/client.py", line 2542, in gather
    return self.sync(
  File "/home/oguzhan/.local/lib/python3.10/site-packages/pogema_toolbox/evaluator.py", line 66, in sequential_backend
    algo = registry.create_algorithm(algo_name, **algo_config)
  File "/home/oguzhan/.local/lib/python3.10/site-packages/pogema_toolbox/registry.py", line 92, in create_algorithm
    return algo_make_func(config)
  File "/mnt/c/Users/Oguzhan Karaarslan/Desktop/repos/pogema-lacam-dcc/algorithms/lacam/inference.py", line 99, in __init__
    self.lacam_lib = LacamLib(cfg.lacam_lib_path)
  File "/mnt/c/Users/Oguzhan Karaarslan/Desktop/repos/pogema-lacam-dcc/algorithms/lacam/inference.py", line 12, in __init__
    self.load_library()
  File "/mnt/c/Users/Oguzhan Karaarslan/Desktop/repos/pogema-lacam-dcc/algorithms/lacam/inference.py", line 15, in load_library
    self._lacam_lib = ctypes.CDLL(self.lib_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: lacam/liblacam.so: cannot open shared object file: No such file or directory